
package com.micromethod.sipmethod.sample.clicktodial;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Click2DialImplService", targetNamespace = "http://clicktodial.sample.sipmethod.micromethod.com/", wsdlLocation = "http://localhost:8080/clicktodial/makecall?wsdl")
public class Click2DialImplService
    extends Service
{

    private final static URL CLICK2DIALIMPLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/clicktodial/makecall?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CLICK2DIALIMPLSERVICE_WSDL_LOCATION = url;
    }

    public Click2DialImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Click2DialImplService() {
        super(CLICK2DIALIMPLSERVICE_WSDL_LOCATION, new QName("http://clicktodial.sample.sipmethod.micromethod.com/", "Click2DialImplService"));
    }

    /**
     * 
     * @return
     *     returns Click2DialImpl
     */
    @WebEndpoint(name = "Click2DialImplPort")
    public Click2DialImpl getClick2DialImplPort() {
        return (Click2DialImpl)super.getPort(new QName("http://clicktodial.sample.sipmethod.micromethod.com/", "Click2DialImplPort"), Click2DialImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Click2DialImpl
     */
    @WebEndpoint(name = "Click2DialImplPort")
    public Click2DialImpl getClick2DialImplPort(WebServiceFeature... features) {
        return (Click2DialImpl)super.getPort(new QName("http://clicktodial.sample.sipmethod.micromethod.com/", "Click2DialImplPort"), Click2DialImpl.class, features);
    }

}
