
package com.micromethod.sipmethod.sample.clicktodial;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Click2DialImpl", targetNamespace = "http://clicktodial.sample.sipmethod.micromethod.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Click2DialImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeCall", targetNamespace = "http://clicktodial.sample.sipmethod.micromethod.com/", className = "com.micromethod.sipmethod.sample.clicktodial.MakeCall")
    @ResponseWrapper(localName = "makeCallResponse", targetNamespace = "http://clicktodial.sample.sipmethod.micromethod.com/", className = "com.micromethod.sipmethod.sample.clicktodial.MakeCallResponse")
    public String makeCall(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
