
package com.micromethod.sipmethod.sample.echo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AddressManager", targetNamespace = "http://echo.sample.sipmethod.micromethod.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressManager {


    /**
     * 
     * @return
     *     returns com.micromethod.sipmethod.sample.echo.MapWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredAddresses", targetNamespace = "http://echo.sample.sipmethod.micromethod.com/", className = "com.micromethod.sipmethod.sample.echo.GetRegisteredAddresses")
    @ResponseWrapper(localName = "getRegisteredAddressesResponse", targetNamespace = "http://echo.sample.sipmethod.micromethod.com/", className = "com.micromethod.sipmethod.sample.echo.GetRegisteredAddressesResponse")
    public MapWrapper getRegisteredAddresses();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeRegister", targetNamespace = "http://echo.sample.sipmethod.micromethod.com/", className = "com.micromethod.sipmethod.sample.echo.RemoveRegister")
    @ResponseWrapper(localName = "removeRegisterResponse", targetNamespace = "http://echo.sample.sipmethod.micromethod.com/", className = "com.micromethod.sipmethod.sample.echo.RemoveRegisterResponse")
    public boolean removeRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
