
package com.voxeo.sipmethod.sample.registrar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AddressManager", targetNamespace = "http://registrar.sample.sipmethod.voxeo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressManager {


    /**
     * 
     * @return
     *     returns com.voxeo.sipmethod.sample.registrar.MapWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisteredAddresses", targetNamespace = "http://registrar.sample.sipmethod.voxeo.com/", className = "com.voxeo.sipmethod.sample.registrar.GetRegisteredAddresses")
    @ResponseWrapper(localName = "getRegisteredAddressesResponse", targetNamespace = "http://registrar.sample.sipmethod.voxeo.com/", className = "com.voxeo.sipmethod.sample.registrar.GetRegisteredAddressesResponse")
    public MapWrapper getRegisteredAddresses();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeRegister", targetNamespace = "http://registrar.sample.sipmethod.voxeo.com/", className = "com.voxeo.sipmethod.sample.registrar.RemoveRegister")
    @ResponseWrapper(localName = "removeRegisterResponse", targetNamespace = "http://registrar.sample.sipmethod.voxeo.com/", className = "com.voxeo.sipmethod.sample.registrar.RemoveRegisterResponse")
    public boolean removeRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
